name: Just echo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    if: github.event.workflow_dispatch
    steps:
      - name: echo
        run: echo 'Hello world'
