name: Just echo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        env:
          event_type: github.event.number
        run: echo 'Hello world' && echo $event_type
