name: Just echo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 'Hello world' && echo ${{ github.event_name }}
