name: Add label
on:
  pull_request:
    types:
      - opened
      - reopoened
jobs:
  add_label_to_issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Label pull requests
        uses: andymckay/labeler@master
        with:
          add-labels: "ci-disabled"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
