name: Add label
on:
  pull_request:
    types: [opened]
jobs:
  add_label_to_issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: 'ci-disabled'
