name: Label PR
on:
  pull_request:
    types: [opened, reopened]
jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Label pull request
        uses: andymckay/labeler@master
        with:
          add-labels: 'ci-disabled'
      - name: Set the job status failed
        uses: actions/github-script@v6
        with:
          script: core.setFailed('backend test is disabled.')
