name: Label PR
on:
  pull_request:
    types: [opened, reopened]
jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label pull request
        uses: andymckay/labeler@master
        with:
          add-labels: 'ci-disabled'
